### ISSUE TITLE
erb rendered into haml template doesn't maintain indentation

### ISSUE THREAD

**Issue by tpitale** [TwP/webby#1]
If I've got a haml template, that is first rendered through erb to create the content that will be edited, the content doesn't maintain the indentation level across multiple lines and so will break when autobuilding.

However, when any template is rendered through a haml layout, the content is properly indented within. Can this be brought down to the templates?

https://gist.github.com/c7b45c2acfbf77bd0a13

**Comment by cboone** [comment]
Your Gist is gone.

**Comment by tpitale** [comment]
Ah, don't worry about it. I was trying to use webby as a library within a rails project, it was a clunky solution to a non-problem.
